agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailsView, AgentDeleteView, AgentUpdateView

app_name = 'agents'

urlpatterns = [
    path('agent-list/', AgentListView.as_view(), name='agent-list'),
    path('agent-create/', AgentCreateView.as_view(), name='agent-create'),
    path('agent-create/details/<int:pk>', AgentDetailsView.as_view(), name='agent-details'),
    path('agent-create/delete/<int:pk>', AgentDeleteView.as_view(), name='agent-delete'),
    path('agent-create/update/<int:pk>', AgentUpdateView.as_view(), name='agent-update'),
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomepageView, SignupView
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView, PasswordResetView
)

urlpatterns = [
    path('', HomepageView.as_view(), name='home'),
    path('', include('leads.urls', namespace='leads')),
    path('', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('admin/', admin.site.urls),
]

leads/urls.py
from django.urls import path
from .views import (
    LeadList, LeadDetails, LeadUpdate, LeadCreate, LeadDelete
)

app_name = 'leads'
urlpatterns = [
    path('lead-list/', LeadList.as_view(), name='lead-list'),
    path('lead-details/<int:pk>/', LeadDetails.as_view(), name='lead-details'),
    path('lead-update/<int:pk>/', LeadUpdate.as_view(), name='lead-update'),
    path('lead-delete/<int:pk>/', LeadDelete.as_view(), name='lead-delete'),
    path('lead-create/', LeadCreate.as_view(), name='lead-create'),
]

agents/models.py
from django.db import models

# Create your models here.

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    is_organization = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class Lead(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    age = models.IntegerField(default=0)
    organization = models.ForeignKey('UserProfile', on_delete=models.CASCADE, default=2)
    agent = models.ForeignKey('Agent', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE, default=2)

    def __str__(self):
        return self.user.username


def post_user_creation_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_creation_signal, sender=User)

agents/forms.py
from leads.models import Agent, UserProfile, User
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class AgentForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    # user = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-control'}), queryset=User.objects.all())
    # organization = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
    #                                       queryset=UserProfile.objects.all())

agents/views.py
from django.shortcuts import render, reverse
from django.views import generic
from leads.models import Agent
from .forms import AgentForm
from django.contrib import messages
from .mixins import OrganizationLoginRequiredMixin


class AgentListView(OrganizationLoginRequiredMixin, generic.ListView):
    template_name = 'agents/agent-list.html'
    queryset = Agent.objects.all()
    context_object_name = 'agents'

    # def get_queryset(self):
    #     user = self.request.user
    #     queryset = Agent.objects.filter(organization=user.userprofile)
    #     return queryset


class AgentDetailsView(OrganizationLoginRequiredMixin, generic.DetailView):
    template_name = 'agents/agent-details.html'
    queryset = Agent.objects.all()


class AgentDeleteView(OrganizationLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agent-delete.html'
    queryset = Agent.objects.all()

    def get_success_url(self):
        messages.error(self.request, 'Agent has been removed along with created leads!')
        return reverse('agents:agent-list')


class AgentCreateView(OrganizationLoginRequiredMixin, generic.CreateView):
    template_name = 'agents/agent-create.html'
    queryset = Agent.objects.all()
    form_class = AgentForm

    # context_object_name = ''

    def get_success_url(self):
        messages.success(self.request, 'New agent has been created!')
        return reverse('agents:agent-list')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organization = False
        user.set_password('agent')
        user.save()
        Agent.objects.create(
            user=user,
            organization=user.userprofile
        )
        return super(AgentCreateView, self).form_valid(form)


class AgentUpdateView(generic.UpdateView):
    template_name = 'agents/agent-update.html'
    queryset = Agent.objects.all()
    form_class = AgentForm

    # context_object_name = ''

    def get_success_url(self):
        messages.success(self.request, 'Agent information has been updated!')
        return reverse('agents:agent-list')

templates/agents/agent-create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="block-header">

        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="body">
                        <form method="post" action="">
                            {% csrf_token %}
                            {{ form }}
                            <input type="submit" class="btn-success" value="Create"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block stylesheet %}
    <!-- Bootstrap Select Css -->
    <link href="{% static 'assets/plugins/bootstrap-select/css/bootstrap-select.css' %}" rel="stylesheet"/>
{% endblock %}

templates/agents/agent-delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="block-header">

        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="body text-center">
                        <h4 class="margin-4 text-center">Are you sure you want to remove this lead from your
                            database? Confirm to delete the item.</h4>
                        <form method="POST" action="">
                            {% csrf_token %}
                            <input type="submit" class="btn-sm btn-success" value="Yes Delete"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/agents/agent-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <h2>Lead Details</h2>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-12">
                    <ul class="breadcrumb float-md-right padding-0">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="zmdi zmdi-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="{% url 'leads:lead-list' %}">Leads</a></li>
                        <li class="breadcrumb-item active">{{ lead.first_name }}</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-lg-4 col-md-12">
                <div class="card">
                    <div class="body m-b-10 widget-user">
                        <img class="rounded-circle" src="{% static 'assets/images/sm/avatar5.jpg' %}" alt="">
                        <div class="wid-u-info">
                            <h5>{{ lead.first_name }} {{ lead.last_name }}</h5>
                            <p class="text-muted m-b-0">Agent: {{ lead.agent }}</p>
                            <small class="text-warning"><b>Age:</b> {{ lead.age }} years</small>
                        </div>
                    </div>
                    <div class="body activities">
                        <div class="streamline b-accent">
                            <div class="sl-item">
                                <div class="sl-content">
                                    <div class="text-muted">Just now</div>
                                    <p>Finished task <a href="" class="text-info">#features 4</a>.</p>
                                </div>
                            </div>
                            <div class="sl-item b-info">
                                <div class="sl-content">
                                    <div class="text-muted">10:30</div>
                                    <p><a href="">@Jessi</a> retwit your post</p>
                                </div>
                            </div>
                            <div class="sl-item b-primary">
                                <div class="sl-content">
                                    <div class="text-muted">12:30</div>
                                    <p>Call to customer <a href="" class="text-info">Jacob</a> and discuss the detail.
                                    </p>
                                </div>
                            </div>
                            <div class="sl-item b-warning">
                                <div class="sl-content">
                                    <div class="text-muted">1 days ago</div>
                                    <p><a href="" class="text-info">Jessi</a> commented your post.</p>
                                </div>
                            </div>
                            <div class="sl-item b-primary">
                                <div class="sl-content">
                                    <div class="text-muted">2 days ago</div>
                                    <p>Call to customer <a href="" class="text-info">Jacob</a> and discuss the detail.
                                    </p>
                                </div>
                            </div>
                            <div class="sl-item b-primary">
                                <div class="sl-content">
                                    <div class="text-muted">3 days ago</div>
                                    <p>Call to customer <a href="" class="text-info">Jacob</a> and discuss the detail.
                                    </p>
                                </div>
                            </div>
                            <div class="sl-item b-warning">
                                <div class="sl-content">
                                    <div class="text-muted">4 Week ago</div>
                                    <p><a href="" class="text-info">Jessi</a> commented your post.</p>
                                </div>
                            </div>
                            <div class="sl-item b-warning">
                                <div class="sl-content">
                                    <div class="text-muted">5 days ago</div>
                                    <p><a href="" class="text-info">Jessi</a> commented your post.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="card">
                    <div class="body">
                        <div class="table-responsive earning-report">
                            <table class="table m-b-0 table-hover">
                                <thead>
                                <tr>
                                    <th colspan="2">User Name</th>
                                    <th>Priority</th>
                                    <th>Earnings</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td style="width:60px;"><span class="rounded"><img
                                            src="assets/images/xs/avatar1.jpg" alt="user" width="50"></span></td>
                                    <td>
                                        <h6>John Smith</h6><small class="text-muted">UI UX Designer</small></td>
                                    <td><span class="badge badge-success">Low</span></td>
                                    <td>$1.9K</td>
                                </tr>
                                <tr class="active">
                                    <td><span class="rounded"><img src="assets/images/xs/avatar2.jpg" alt="user"
                                                                   width="50"></span></td>
                                    <td>
                                        <h6>Hossein Shams</h6><small class="text-muted">Project Manager</small></td>
                                    <td><span class="badge badge-info">Medium</span></td>
                                    <td>$2.9K</td>
                                </tr>
                                <tr>
                                    <td><span class="round round-success"><img src="assets/images/xs/avatar3.jpg"
                                                                               alt="user" width="50"></span></td>
                                    <td>
                                        <h6>Maryam Amiri</h6><small class="text-muted">Angular Developer</small></td>
                                    <td><span class="badge badge-primary">High</span></td>
                                    <td>$32.9K</td>
                                </tr>
                                <tr>
                                    <td><span class="round round-primary"><img src="assets/images/xs/avatar4.jpg"
                                                                               alt="user" width="50"></span></td>
                                    <td>
                                        <h6>Tim Hank</h6><small class="text-muted">Frontend</small></td>
                                    <td><span class="badge badge-danger">Low</span></td>
                                    <td>$11.9K</td>
                                </tr>
                                <tr>
                                    <td><span class="round round-warning"><img src="assets/images/xs/avatar5.jpg"
                                                                               alt="user" width="50"></span></td>
                                    <td>
                                        <h6>Fidel Tonn</h6><small class="text-muted">Content Writer</small></td>
                                    <td><span class="badge badge-warning">High</span></td>
                                    <td>$2.5K</td>
                                </tr>
                                <tr>
                                    <td><span class="round round-danger"><img src="assets/images/xs/avatar6.jpg"
                                                                              alt="user" width="50"></span></td>
                                    <td>
                                        <h6>Frank Camly</h6><small class="text-muted">Graphic Design</small></td>
                                    <td><span class="badge badge-info">High</span></td>
                                    <td>$12.7K</td>
                                </tr>
                                <tr>
                                    <td><span class="round round-primary"><img src="assets/images/xs/avatar4.jpg"
                                                                               alt="user" width="50"></span></td>
                                    <td>
                                        <h6>Tim Hank</h6><small class="text-muted">Frontend</small></td>
                                    <td><span class="badge badge-danger">Low</span></td>
                                    <td>$11.9K</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/agents/agent-list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <h2>All Agents List</h2>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-12">
                    <ul class="breadcrumb float-md-right padding-0">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="zmdi zmdi-home"></i></a></li>
                        <li class="breadcrumb-item active">Lead List</li>
                    </ul>
                </div>
            </div>
        </div>
        {% if messages %}
            <div class="row clearfix">
                <div class="col-md-12">
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger">{{ message }} {{ message.tags }}</div>
                        {% elif message.tags == 'success' %}
                            <div class="alert alert-success">{{ message }}</div>
                        {% else %}
                            <div class="alert alert-info">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="row clearfix">
            <a class="badge badge-info pull-right" href="{% url 'agents:agent-create' %}">Create New Agent</a>
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="body project_report">
                        <div class="table-responsive">
                            <table class="table m-b-0 table-hover">
                                <thead>
                                <tr>
                                    <th>Status</th>
                                    <th>Agents</th>
                                    <th>Leads</th>
                                    <th>User</th>
                                    <th>User Profile</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for agent in agents %}
                                    <tr>
                                        <td>
                                            <span class="badge badge-success">Active</span>
                                        </td>
                                        <td class="project-title">
                                            <h6>
                                                <a href="{% url 'agents:agent-details' agent.id %}">{{ agent.user.username }}</a>
                                            </h6>
                                            <small>Created 14.Mar.2018</small>
                                        </td>
                                        <td>
                                            {{ agent.lead_set.count }}
                                        </td>
                                        <td>{{ agent.user.username }}</td>
                                        <td>
                                            {{ agent.organization.user.username }}
                                        </td>
                                        <td class="project-actions">
                                            <a href="{% url 'agents:agent-details' agent.id %}"
                                               class="btn btn-neutral btn-sm"><i class="zmdi zmdi-eye"></i></a>
                                            <a href="{% url 'agents:agent-update' agent.id %}"
                                               class="btn btn-neutral btn-sm"><i
                                                    class="zmdi zmdi-edit"></i></a>
                                            <a href="{% url 'agents:agent-delete' agent.id %}"
                                               class="btn btn-neutral btn-sm"><i class="zmdi zmdi-delete"></i></a>

                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/agents/agent-update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <h2>Update Agent</h2>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-12">
                    <ul class="breadcrumb float-md-right padding-0">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="zmdi zmdi-home"></i></a></li>
                        <li class="breadcrumb-item active">Agents</li>
                    </ul>
                </div>
            </div>
        </div>
        {% if messages %}
            <div class="row clearfix">
                <div class="col-md-12">
                    {% for message in messages %}
                        {% if message.tags == 'error' %}
                            <div class="alert alert-danger">{{ message }} {{ message.tags }}</div>
                        {% elif message.tags == 'success' %}
                            <div class="alert alert-success">{{ message }}</div>
                        {% else %}
                            <div class="alert alert-info">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="row clearfix">
            <a class="badge badge-info pull-right" href="{% url 'agents:agent-create' %}">Create New Agent</a>
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="body project_report">
                        <form method="post">
                            {% csrf_token %}
                            {{ form }}
                            <input type="submit" class="btn btn-success" value="Update"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block stylesheet %}
    <!-- Bootstrap Select Css -->
    <link href="{% static 'assets/plugins/bootstrap-select/css/bootstrap-select.css' %}" rel="stylesheet"/>
{% endblock %}