agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailsView, AgentDeleteView, AgentUpdateView

app_name = 'agents'

urlpatterns = [
    path('agent-list/', AgentListView.as_view(), name='agent-list'),
    path('agent-create/', AgentCreateView.as_view(), name='agent-create'),
    path('agent-create/details/<int:pk>', AgentDetailsView.as_view(), name='agent-details'),
    path('agent-create/delete/<int:pk>', AgentDeleteView.as_view(), name='agent-delete'),
    path('agent-create/update/<int:pk>', AgentUpdateView.as_view(), name='agent-update'),
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomepageView, SignupView
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView, PasswordResetView
)

urlpatterns = [
    path('', HomepageView.as_view(), name='home'),
    path('', include('leads.urls', namespace='leads')),
    path('', include('agents.urls', namespace='agents')),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('admin/', admin.site.urls),
]

leads/urls.py
from django.urls import path
from .views import (
    LeadList, LeadDetails, LeadUpdate, LeadCreate, LeadDelete
)

app_name = 'leads'
urlpatterns = [
    path('lead-list/', LeadList.as_view(), name='lead-list'),
    path('lead-details/<int:pk>/', LeadDetails.as_view(), name='lead-details'),
    path('lead-update/<int:pk>/', LeadUpdate.as_view(), name='lead-update'),
    path('lead-delete/<int:pk>/', LeadDelete.as_view(), name='lead-delete'),
    path('lead-create/', LeadCreate.as_view(), name='lead-create'),
]

templates/include/menu-container.html
<div class="menu-container">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul class="h-menu">
                    <li><a href="{% url 'home' %}"><i class="zmdi zmdi-home"></i></a></li>
                    <li><a href="{% url 'home' %}">Home</a>
                    </li>
                    <li><a href="{% url 'leads:lead-list' %}">Leads</a></li>
                    {% if request.user.is_organization %}
                        <li><a href="{% url 'agents:agent-list' %}">Agents</a></li>
                    {% endif %}
                    <li><a href="javascript:void(0)">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

templates/include/navbar.html
{% load static %}
<nav class="navbar">
    <div class="container">
        <ul class="nav navbar-nav">
            <li>
                <div class="navbar-header">
                    <a href="javascript:void(0);" class="h-bars"></a>
                    <a class="navbar-brand" href="{% url 'home' %}"><img
                            src="{% static 'assets/images/logo-black.svg' %}" width="35" alt="DjCrm"><span
                            class="m-l-10">DjCrm</span></a>
                </div>
            </li>
            <li class="search_bar">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search...">
                </div>
            </li>
            {% if request.user.is_superuser %}
                <li class="dropdown"><a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                        role="button"><i class="zmdi zmdi-apps"></i></a>
                    <ul class="dropdown-menu pullDown">
                        <li><a href="/admin"><i class="zmdi zmdi-email m-r-10"></i><span>Admin</span></a></li>
                        <li><a href="contact.html"><i
                                class="zmdi zmdi-accounts-list m-r-10"></i><span>Contacts</span></a>
                        </li>
                        <li><a href="chat.html"><i class="zmdi zmdi-comment-text m-r-10"></i><span>Chat</span></a></li>
                        <li><a href="invoices.html"><i class="zmdi zmdi-arrows m-r-10"></i><span>Invoices</span></a>
                        </li>
                        <li><a href="events.html"><i
                                class="zmdi zmdi-calendar-note m-r-10"></i><span>Calendar</span></a>
                        </li>
                        <li><a href="javascript:void(0)"><i class="zmdi zmdi-arrows m-r-10"></i><span>Notes</span></a>
                        </li>
                        <li><a href="javascript:void(0)"><i
                                class="zmdi zmdi-view-column m-r-10"></i><span>Taskboard</span></a>
                        </li>
                    </ul>
                </li>
            {% endif %}
            <li class="float-right">
                {#            <a href="javascript:void(0);" class="fullscreen" data-provide="fullscreen"><i class="zmdi zmdi-fullscreen"></i></a>#}
                {#            <a href="javascript:void(0);" class="btn_overlay"><i class="zmdi zmdi-sort-amount-desc"></i></a>#}
                {#            <a href="javascript:void(0);" class="js-right-sidebar"><i class="zmdi zmdi-settings zmdi-hc-spin"></i></a>#}
                {% if request.user.is_authenticated %}
                    <span>Logged in as <strong>{{ request.user.username }}</strong></span>
                    <a href="{% url 'logout' %}" class="mega-menu"><i class="zmdi zmdi-power"></i></a>
                {% else %}
                    <a href="{% url 'signup' %}" class="js-right-sidebar"><i
                            class="zmdi zmdi-account-add"></i></a>
                    <a href="{% url 'login' %}" class="js-right-sidebar"><i
                            class="zmdi zmdi-sign-in"></i></a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>